---

version: 1

filters:
  infoFilter:
    (): __main__.infoFilter

formatters:
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: mnt/shazam_fetch.log
    formatter: extended

loggers:
  dev:
    level: INFO
    handlers: [file_handler, console]
  uat:
    level: WARNING
    handlers: [file_handler]
  prod:
    level: ERROR
    handlers: [ file_handler ]

root:
  handlers: [file_handler, console]